# A tmux.conf

# -- general -----------------
set -g default-terminal "screen-256color"

setw -g xterm-keys on
set -s escape-time 1

set -g repeat-time 200
set -g lock-after-time 0

# screen compatible prefix
unbind-key C-b
set -g prefix C-a
bind C-a send-prefix

set -g history-limit 100000

set -g mouse on

# rebind refresh-client to reload this
bind r source-file ~/.tmux.conf \; display "~/.tmux.conf sourced"

# -- display -----------------
# start windows and panes at 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

setw -g allow-rename off
setw -g automatic-rename on
set -g renumber-windows on
set -g set-titles on

set -g status-interval 5
set -s focus-events on
set -g monitor-activity on
set -g visual-activity on
set -g bell-action any
set -g activity-action none

# -- navigation --------------
# sessions
bind C-c new-session
bind C-f command-prompt -p find-session 'switch-client -t %%'
bind BTab switch-client -1

# make it vimmy
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

# pane navigation
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# pane swapping (kind of sucks oh well)
bind J swap-pane -D
bind K swap-pane -U
bind L swap-pane -D
bind H swap-pane -U # heh, dudu

# pane resizing
bind -r < resize-pane -L 2
bind -r + resize-pane -D 2
bind -r - resize-pane -U 2
bind -r > resize-pane -R 2

# window navigation
unbind n
unbind p
bind -r C-h previous-window
bind -r C-l next-window
bind Tab last-window

# -- vi copy-mode ------------
setw -g mode-keys vi
set  -g status-keys vi
bind Enter copy-mode

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection

# -- buffers -----------------
bind b list-buffers
bind p paste-buffer
bind P choose-buffer

# -- theme -------------------
# dracula colors
dracula_background='#282a36'
dracula_current_line='#6272a4'
dracula_selection='#44475a'
dracula_foreground='#f8f8f2'
dracula_comment='#6272a4'
dracula_red='#ff5555'
dracula_orange='#ffb86c'
dracula_yellow='#f1fa8c'
dracula_green='#50fa7b'
dracula_cyan='#8be9fd'
dracula_purple='#bd93f9'
dracula_pink='#ff79c6'

set -g status-left-length 100
set -g status-left "#{?client_prefix,#[bg=$dracula_yellow],} #h "

set -g  status-right-length 100
set -g  status-right "#[fg=$dracula_pink,bold] #(~/tmux/scripts/cpu-info.sh)"
set -ga status-right "#[fg=$dracula_cyan,bold] #(~/tmux/scripts/ram-info.sh)"
set -ga status-right "#[default] %a %m/%d %R "

setw -g window-status-format         " #I #W#{?window_flags,#[fg=$dracula_pink]#F,} "
setw -g window-status-current-format " #I #W#{?window_flags,#[fg=$dracula_pink]#F,} "
setw -g window-status-separator      ""

setw -g pane-border-style            "fg=$dracula_selection"
setw -g pane-active-border-style     "fg=$dracula_purple"
set  -g message-style                "fg=$dracula_foreground,bg=$dracula_selection"
set  -g status-style                 "fg=$dracula_foreground,bg=$dracula_selection"
set  -g status-left-style            "fg=$dracula_background,bg=$dracula_green"
set  -g status-right-style           "default"
setw -g window-style                 "default"
setw -g window-active-style          "default"
set  -g window-status-style          "fg=$dracula_foreground,bg=$dracula_selection"
set  -g window-status-current-style  "fg=$dracula_foreground,bg=$dracula_current_line"
set  -g window-status-activity-style "fg=$dracula_selection,bg=$dracula_foreground"
set  -g window-status-bell-style     "fg=$dracula_selection,bg=$dracula_foreground,bold"
set  -g window-status-last-style     "default"
setw -g mode-style                   "bg=$dracula_selection"


